# Generated by Django 4.0.4 on 2022-05-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default=' ', max_length=200, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
