# Generated by Django 4.0.4 on 2022-05-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0004_alter_appointment_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='uploads/')),
                ('title', models.CharField(max_length=30)),
                ('desciption', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
            preserve_default=False,
        ),
    ]
